name: Publish

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Build, test and publish package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/termaconfig/
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: venv

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest

      - name: Package project
        run: poetry build

      - name: Upload build artifact
        uses: actions/upload-artifact@v5
        with:
          name: build-artifact
          path: dist/*.tar.gz

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    needs: pypi-publish
    runs-on: ubuntu-latest
    name: Create Github release
    steps:
      - name: Retrieve built package
        uses: actions/download-artifact@v5
        with:
          name: build-artifact

      - name: Create release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: dist/*.tar.gz
